name:                forest
version:             0.1.0.0
github:              "mitchellvitez/forest"
license:             BSD3
author:              "Mitchell Vitez"
maintainer:          "mitchell@vitez.me"
copyright:           "Mitchell Vitez"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mitchellvitez/forest#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  forest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forest
    - hspec
